[package]
name = "dynamic-traits"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal = "1.0.0"

# Dependencies for the 'hal' module
embassy-hal-internal = "0.2.0"
critical-section = "1.2.0"
embedded-hal-async = "1.0.0"
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
